services:
  budget-postgres:
    container_name: db-budget
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Ensure this is set
    ports:
      - "5433:5432"
    volumes:
      - budget-data-volume:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}",
        ]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: always

volumes:
  budget-data-volume:
